accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<slug:username>/", views.UserProfileView.as_view(), name="user_profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path(
        "<str:username>/following_list/",
        views.FollowingListView.as_view(),
        name="following_list",
    ),
    path(
        "<str:username>/follower_list/",
        views.FollowerListView.as_view(),
        name="follower_list",
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

tweets/models.py
from django.db import models
from django.urls import reverse

from accounts.models import User


class Tweet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(verbose_name="内容", max_length=140)
    created_at = models.DateTimeField(verbose_name="作成日", auto_now_add=True)

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse("tweets:detail", kwargs={"pk": self.pk})


class Like(models.Model):
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["tweet", "user"],
                name="like_unique",
            )
        ]

    def __str__(self):
        return f"{self.user} likes {self.tweet}"

tweets/forms.py
from django import forms
from django.forms import ModelForm

from .models import Tweet


class TweetForm(ModelForm):
    content = forms.CharField(
        label="",
        max_length=140,
        widget=forms.Textarea(attrs={"rows": 4, "cols": 35, "placeholder": "いまどうしてる？"}),
    )

    class Meta:
        model = Tweet
        fields = ("content",)

tweets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, View

from .forms import TweetForm
from .models import Like, Tweet

# Create your views here.


class HomeView(LoginRequiredMixin, ListView):
    model = Tweet
    template_name = "tweets/home.html"
    context_object_name = "tweets"

    def get_queryset(self):
        return Tweet.objects.select_related("user").order_by("-created_at")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liked_list"] = Like.objects.filter(user=self.request.user).values_list(
            "tweet", flat=True
        )
        return context


class TweetCreateView(LoginRequiredMixin, CreateView):
    template_name = "tweets/tweet_create.html"
    form_class = TweetForm
    success_url = reverse_lazy("tweets:home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TweetDetailView(LoginRequiredMixin, DetailView):
    model = Tweet
    template_name = "tweets/tweet_detail.html"


class TweetDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Tweet
    template_name = "tweets/tweet_delete.html"
    success_url = reverse_lazy("tweets:home")

    def test_func(self):
        tweet = self.get_object()
        return self.request.user == tweet.user


class LikeView(LoginRequiredMixin, View):
    def post(self, request, **kwargs):
        pk = self.kwargs["pk"]
        tweet = get_object_or_404(Tweet, pk=pk)
        user = self.request.user
        Like.objects.get_or_create(tweet=tweet, user=user)
        context = {
            "tweet_pk": tweet.pk,
            "like_counter": tweet.like_set.count(),
        }
        return JsonResponse(context)


class UnlikeView(LoginRequiredMixin, View):
    def post(self, request, **kwargs):
        pk = self.kwargs["pk"]
        tweet = get_object_or_404(Tweet, pk=pk)
        user = self.request.user
        like = Like.objects.filter(tweet=tweet, user=user)
        like.delete()
        context = {
            "tweet_pk": tweet.pk,
            "like_counter": tweet.like_set.count(),
        }
        return JsonResponse(context)

tweets/templates/tweets/home.html
{% extends 'base.html' %}


{% block title %}ホーム{% endblock title %}


{% block content %}
{% if messages %}
	{% for message in messages %}
		<div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
	{% endfor %}
{% endif %}
<h2>ホーム</h2>
{% for tweet in tweets %}
        <div class="card">
            <b class="card-header"><a href="{% url 'accounts:user_profile' tweet.user %}">{{ tweet.user }}</a></b>
            <div class="card-body">
                <p class="card-text">{{ tweet.content }}</p>
            </div>
            <div class="card-footer text-muted">
                {{ tweet.created_at }}
                <span><a href="{{ tweet.get_absolute_url }}">詳細</a></span>
                {% include 'tweets/like.html' %}
            </div>
        </div>
        <br>
{% endfor %}
{% endblock content %}
{% block extrajs %}
{% include 'tweets/script.html' %}
{% endblock extrajs %}

tweets/templates/tweets/like.html
{% if tweet.pk in liked_list %}
<button type="button" style="border:none;background:none" class="like-or-unlike-button"
    id="like-for-tweet-{{ tweet.pk }}" data-tweet-pk="{{ tweet.pk }}" data-is-liked="true">
    <span class="btn btn-danger btn-sm rounded-pill" id="ajax-like-icon-{{ tweet.pk }}">いいね</span>
</button>
{% else %}
    <button type="button" style="border:none;background:none" class="like-or-unlike-button"
        id="like-for-tweet{{ tweet.pk }}" data-tweet-pk="{{ tweet.pk }}" data-is-liked="false">
        <span class="btn btn-outline-danger btn-sm rounded-pill" id="ajax-like-icon-{{ tweet.pk }}">いいね</span>
    </button>
{% endif %}
<b id="ajax-like-count-{{ tweet.pk }}">{{ tweet.like_set.count }}</b>

tweets/templates/tweets/script.html
<script type="text/javascript">
    const getCookie = name => {
        if (document.cookie && document.cookie !== '') {
            for (const cookie of document.cookie.split(';')) {
                const [key, value] = cookie.trim().split('=');
                if (key === name) {
                    return decodeURIComponent(value);
                    }
                }
            }
        };

    const csrftoken = getCookie('csrftoken');

    const likeLinks = document.getElementsByClassName('like-or-unlike-button');
    for (const likeLink of likeLinks) {
        likeLink.addEventListener('click', async (e) => {
            let url = '';
            const element = e.currentTarget;
            if (element.dataset.isLiked == 'true') {
                url = "{% url 'tweets:unlike' 0 %}".replace("0", element.getAttribute('data-tweet-pk'));
            } else {
                url = "{% url 'tweets:like' 0 %}".replace("0", element.getAttribute('data-tweet-pk'));
            }
            try {
                const config = {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrftoken,
                    }};
                const response = await fetch(url, config);
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                const data = await response.json();

                const counter = document.getElementById('ajax-like-count-' + data.tweet_pk);
                counter.textContent = data.like_counter;
                const icon = document.getElementById('ajax-like-icon-' + data.tweet_pk);
                if (element.dataset.isLiked == 'false') {
                    element.dataset.isLiked = 'true';
                    icon.classList.replace('btn-outline-danger', 'btn-danger');
                    icon.id = ('ajax-like-icon-' + data.tweet_pk);
                } else {
                    element.dataset.isLiked = 'false';
                    icon.classList.replace('btn-danger', 'btn-outline-danger');
                    icon.id = ('ajax-like-icon-' + data.tweet_pk);
                }
            } catch (e) {
                alert(e);
            }
        });
    };
</script>

tweets/templates/tweets/tweet_create.html
{% extends 'base.html' %}


{% block title %}新規投稿{% endblock title %}


{% block content %}
<div class="d-flex justify-content-center">
    <div class="card text-center">
        <div class="card-header">
            <b>新規作成</b>
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                    <button type="submit" class="btn btn-primary btn-lg">ツイートする</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

tweets/templates/tweets/tweet_delete.html
{% extends 'base.html' %}


{% block title %}注意{% endblock title %}


{% block content %}
<h2>本当に削除してよろしいですか？</h2>
<div class="card">
    <b class="card-header">{{ tweet.user }}</b>
    <div class="card-body">
        <p class="card-text">{{ tweet.content }}</p>
    </div>
    <div class="card-footer text-muted">
        {{ tweet.created_at }}
    </div>
    <div class="d-flex justify-content-start">
        <div class="btn-group" role="group" aria-label="Basic example">
            <button type="button" class="btn btn-primary btn-lg" onclick="history.back(-1)">戻る</button>
            <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-lg">削除</button>
            </form>
        </div>
    </div>
{% endblock content %}

tweets/templates/tweets/tweet_detail.html
{% extends 'base.html' %}


{% block title %}詳細{% endblock title %}


{% block content %}
<div class="card">
    <b class="card-header"><a href="{% url 'accounts:user_profile' tweet.user %}">{{ tweet.user }}</a></b>
    <div class="card-body">
        <p class="card-text">{{ tweet.content }}</p>
    </div>
    <div class="card-footer text-muted">
        {{ tweet.created_at }}
        <b>{{ tweet.like_set.count }}件のいいね</b>
    </div>
    <div class="d-flex justify-content-start">
        <div class="btn-group" role="group" aria-label="Basic example">
            <a href="{% url 'tweets:home' %}"><button type="button" class="btn btn-primary">戻る</button></a>
            {% if request.user == tweet.user %}
            <a href="{% url 'tweets:delete' tweet.pk %}"><button type="button" class="btn btn-danger">削除</button></a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}