accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<slug:username>/", views.UserProfileView.as_view(), name="user_profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path(
        "<str:username>/following_list/",
        views.FollowingListView.as_view(),
        name="following_list",
    ),
    path(
        "<str:username>/follower_list/",
        views.FollowerListView.as_view(),
        name="follower_list",
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField(max_length=254)
    birth_date = models.DateField(
        verbose_name="誕生日",
        null=True,
        blank=True,
    )
    self_introduction = models.TextField(
        verbose_name="自己紹介",
        max_length=160,
        null=True,
        blank=True,
        default="未設定",
    )


class FriendShip(models.Model):
    followee = models.ForeignKey(
        User,
        related_name="followee",
        on_delete=models.CASCADE,
    )
    follower = models.ForeignKey(
        User,
        related_name="follower",
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["followee", "follower"], name="unique_friendship"
            )
        ]

    def __str__(self):
        return f"{self.follower.username} follows {self.followee.username}"

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
        )

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, View

from tweets.models import Like, Tweet

from .forms import SignUpForm
from .models import FriendShip, User

# Create your views here.


class SignUpView(CreateView):
    template_name = "accounts/sign_up.html"
    form_class = SignUpForm
    success_url = reverse_lazy("tweets:home")

    def form_valid(self, form):
        result = super().form_valid(form)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return result


class UserProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "accounts/profile.html"
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        context["tweets"] = (
            Tweet.objects.select_related("user")
            .filter(user=user)
            .order_by("-created_at")
        )
        context["following_count"] = FriendShip.objects.filter(follower=user).count()
        context["follower_count"] = FriendShip.objects.filter(followee=user).count()
        context["connection_exists"] = FriendShip.objects.filter(
            follower=self.request.user, followee=user
        ).exists()
        context["liked_list"] = Like.objects.filter(user=self.request.user).values_list(
            "tweet", flat=True
        )
        return context


class FollowView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        follower = self.request.user
        try:
            followee = User.objects.get(username=self.kwargs["username"])
        except User.DoesNotExist:
            messages.warning(request, "指定されたユーザーは存在しません。")
            raise Http404

        if follower == followee:
            messages.warning(request, "自分自身はフォローできません。")
            return render(request, "tweets/home.html")
        elif FriendShip.objects.filter(follower=follower, followee=followee).exists():
            messages.warning(request, f"あなたは{ followee.username }をすでにフォローしています。")
            return render(request, "tweets/home.html")
        else:
            FriendShip.objects.create(follower=follower, followee=followee)
            messages.success(request, f"{ followee.username }をフォローしました。")
            return HttpResponseRedirect(reverse("tweets:home"))


class UnFollowView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        follower = self.request.user
        try:
            followee = User.objects.get(username=self.kwargs["username"])
        except User.DoesNotExist:
            messages.warning(request, "指定されたユーザーは存在しません。")
            raise Http404

        if follower == followee:
            messages.warning(request, "自分自身のフォローを外すことはできません。")
            return render(request, "tweets/home.html")
        elif FriendShip.objects.filter(follower=follower, followee=followee).exists():
            FriendShip.objects.filter(follower=follower, followee=followee).delete()
            messages.success(request, f"{ followee.username }のフォローを解除しました。")
            return HttpResponseRedirect(reverse("tweets:home"))
        else:
            messages.warning(request, f"{followee.username}はフォローしていません")
            return render(request, "tweets/home.html")


class FollowingListView(LoginRequiredMixin, ListView):
    template_name = "accounts/following_list.html"
    model = FriendShip

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.kwargs["username"]
        follower = get_object_or_404(User, username=username)
        context["username"] = username
        context["following_list"] = (
            FriendShip.objects.select_related("follower")
            .filter(follower=follower)
            .order_by("-created_at")
        )
        return context


class FollowerListView(LoginRequiredMixin, ListView):
    template_name = "accounts/follower_list.html"
    model = FriendShip

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.kwargs["username"]
        followee = get_object_or_404(User, username=username)
        context["username"] = username
        context["follower_list"] = (
            FriendShip.objects.select_related("followee")
            .filter(followee=followee)
            .order_by("-created_at")
        )
        return context

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="ja">

    <head>
        <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
                rel="stylesheet"
                integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
                crossorigin="anonymous">
        <title>{% block title %}{% endblock title %}</title>
    </head>

    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <h3><a class="nav-link" href="#">Twitter Clone</a></h3>
                <div class="d-flex">
                    <p class="nav-link"><a href="#">ログイン</a></p>
                    <p><button type="button" class="btn btn-outline-primary"><a href="{% url 'accounts:signup' %}">登録</a></button></p>
                </div>
            </div>
        </nav>

        {% block content %}
        {% endblock content %}

    </body>

</html>

accounts/templates/accounts/follower_list.html
{% extends "base.html" %}


{% block title %}フォロワー一覧{% endblock title %}


{% block content %}
<h2>{{ username }}のフォロワー一覧</h2>
{% for follower in follower_list %}
<div class="card text-center">
    <div class="card-header">
        <b>{{ follower.follower }}</b>
    </div>
    <div class="card-body">
        <a href="{% url 'accounts:user_profile' follower.follower.username %}"><button type="button" class="btn btn-outline-primary">プロフィールへ</button></a>
    </div>
</div>
<br>
{% endfor %}
{% endblock %}

accounts/templates/accounts/following_list.html
{% extends "base.html" %}


{% block title %}フォロー一覧{% endblock title %}


{% block content %}
<h2>{{ username }}のフォロー一覧</h2>
{% for following in following_list %}
<div class="card text-center">
    <div class="card-header">
        <b>{{ following.followee }}</b>
    </div>
    <div class="card-body">
        <a href="{% url 'accounts:user_profile' following.followee.username %}"><button type="button" class="btn btn-outline-primary">プロフィールへ</button></a>
    </div>
</div>
<br>
{% endfor %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block title %}ログイン{% endblock title %}


{% block content %}
    <div class="d-flex justify-content-center">
        <h2>ログイン</h2>
    </div>
    <div class="d-flex justify-content-center">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-primary">ログイン</button>
        </form>
    </div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}


{% block title %}プロフィール{% endblock title %}


{% block content %}
<h2>プロフィール</h2>
<div class="card">
    <div class="card-header">
        <div class="d-flex justify-content-center">
            <b>{{ user.username }}</b>
        </div>
        <hr>
        <div class="d-flex justify-content-center">
            {% if request.user == user %}
                <a href="#">プロフィール編集</a>
            {% elif connection_exists %}
                <form method="POST" action="{% url 'accounts:unfollow' user.username %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-secondary">フォロー解除</button>
                </form>
            {% else %}
                <form method="POST" action="{% url 'accounts:follow' user.username %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-info">フォロー</button>
                </form>
            {% endif %}
        </div>
    </div>
    <div class="card-body">
        <p class="card-text">誕生日:{{ user.birth_date }}</p>
        <p class="card-text">自己紹介:{{ user.self_introduction }}</p>
        <div class="d-flex flex-row">
            <div class="p-2 bd-highlight"><p class="card-text">フォロー中: <a href="{% url 'accounts:following_list' user.username %}">{{ following_count }}</a></p></div>
            <div class="p-2 bd-highlight"><p class="card-text">フォロワー: <a href="{% url 'accounts:follower_list' user.username %}">{{ follower_count }}</a></p></div>
        </div>
    </div>
</div>
<hr>
<p><b>{{ user.username }}のツイート</b></p>
{% for tweet in tweets %}
        <div class="card">
            <b class="card-header">{{ tweet.user }}</b>
            <div class="card-body">
                <p class="card-text">{{ tweet.content }}</p>
            </div>
            <div class="card-footer text-muted">
                {{ tweet.created_at }}
                {% include 'tweets/like.html' %}
            </div>
            {% if request.user == tweet.user %}
                <a href="{% url 'tweets:delete' tweet.pk %}"><button type="button" class="btn btn-danger">削除</button></a>
            {% endif %}
        </div>
        <br>
{% endfor %}
{% endblock content %}
{% block extrajs %}
{% include 'tweets/script.html' %}
{% endblock extrajs %}

accounts/templates/accounts/sign_up.html
{% extends 'base.html' %}


{% block title %}登録{% endblock title %}


{% block content %}

    <div class="d-flex justify-content-center">
        <h2>ユーザー登録</h2>
    </div>
    <div class="d-flex justify-content-center">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-outline-primary">登録</button>
        </form>
    </div>
{% endblock content %}