accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<slug:username>/", views.UserProfileView.as_view(), name="user_profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path(
        "<str:username>/following_list/",
        views.FollowingListView.as_view(),
        name="following_list",
    ),
    path(
        "<str:username>/follower_list/",
        views.FollowerListView.as_view(),
        name="follower_list",
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.WelcomeView.as_view(), name="index")
]

templates/base.html
<!DOCTYPE html>
<html lang="ja">

    <head>
        <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous">
        <title>{% block title %}{% endblock title %}</title>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                {% if user.is_authenticated %}
                <h3><a class="nav-link" href="{% url 'tweets:home' %}">Twitter Clone</a></h3>
                {% else %}
                <h3><a class="nav-link" href="{% url 'welcome:index' %}">Twitter Clone</a></h3>
                {% endif %}
                <div class="d-flex">
                    {% if user.is_authenticated %}
                    <p class="nav-link"><a href="{% url 'accounts:logout' %}"><button type="button" class="btn btn-outline-primary">ログアウト</button></a></p>
                    <p class="nav-link"><a href="{% url 'accounts:user_profile' request.user %}"><button type="button" class="btn btn-outline-primary">{{ request.user }}</button></a></p>
                    {% else %}
                    <p class="nav-link"><a href="{% url 'accounts:login' %}"><button type="button" class="btn btn-outline-primary">ログイン</button></a></p>
                    <p class="nav-link"><a href="{% url 'accounts:signup' %}"><button type="button" class="btn btn-outline-primary">登録</button></a></p>
                    {% endif %}
                </div>
            </div>
        </nav>
        <br>
        <div class="container">
            <div class="row">
                {% if user.is_authenticated %}
                    <div class="col-2">
                            <a href="{% url 'tweets:home' %}"><button type="button" class="btn btn-outline-primary btn-lg w-100">ホーム</button></a>
                            <a href="{% url 'tweets:create' %}"><button type="button" class="btn btn-primary btn-lg w-100">ツイートする</button></a>
                    </div>
                {% endif %}
                <div class="col">
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
        {% block extrajs %}
        {% endblock extrajs %}
    </body>

</html>